"""empty message

Revision ID: 1b1bcf2eec9f
Revises: ed09fdf09ee3
Create Date: 2024-09-11 17:13:23.567835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1bcf2eec9f'
down_revision = 'ed09fdf09ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardholder_name', sa.String(length=100), nullable=False),
    sa.Column('last_four_digits', sa.String(length=4), nullable=False),
    sa.Column('expiration_year', sa.Integer(), nullable=False),
    sa.Column('expiration_month', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('issuing_bank', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('most_used', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_creditcard_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creditcard'))
    )
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('delivery_type', sa.Enum('HOME', 'SEVEN_ELEVEN', 'FAMILYMART', name='deliverytype'), nullable=False),
    sa.Column('store_code', sa.String(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name=op.f('fk_delivery_address_id_address')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_delivery_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery'))
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH_ON_DELIVERY', 'CREDIT_CARD', name='paymentmethod'), nullable=False),
    sa.Column('creditcard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], name=op.f('fk_order_coupon_id_coupon')),
    sa.ForeignKeyConstraint(['creditcard_id'], ['creditcard.id'], name=op.f('fk_order_creditcard_id_creditcard')),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], name=op.f('fk_order_delivery_id_delivery')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_order_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('delivery')
    op.drop_table('creditcard')
    # ### end Alembic commands ###
