"""empty message

Revision ID: 3e41d9ab4793
Revises: 
Create Date: 2024-09-10 17:40:36.759929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e41d9ab4793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('state_province_county', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address_line_1', sa.String(length=100), nullable=False),
    sa.Column('address_line_2', sa.String(length=100), nullable=True),
    sa.Column('address_line_3', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(), nullable=False),
    sa.Column('other_address_details', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], name=op.f('fk_category_parent_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='discounttype'), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('min_purchase', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon'))
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('home_phone_number', sa.String(length=30), nullable=False),
    sa.Column('mobile_phone_number', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name=op.f('fk_user_address_id_address')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('home_phone_number', name=op.f('uq_user_home_phone_number')),
    sa.UniqueConstraint('mobile_phone_number', name=op.f('uq_user_mobile_phone_number')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_variant_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variant'))
    )
    op.create_table('user__coupon',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], name=op.f('fk_user__coupon_coupon_id_coupon')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user__coupon_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'coupon_id', name=op.f('pk_user__coupon'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__coupon')
    op.drop_table('variant')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('coupon')
    op.drop_table('category')
    op.drop_table('address')
    # ### end Alembic commands ###
