"""empty message

Revision ID: ed09fdf09ee3
Revises: 109e80fcd946
Create Date: 2024-09-11 16:38:20.929733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed09fdf09ee3'
down_revision = '109e80fcd946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coupon',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], name=op.f('fk_user_coupon_coupon_id_coupon')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_coupon_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'coupon_id', name=op.f('pk_user_coupon'))
    )
    op.drop_table('user__coupon')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint('fk_address_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_address_id_address'), 'address', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_address_id_address'), type_='foreignkey')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_address_user_id_user', 'user', ['user_id'], ['id'])

    op.create_table('user__coupon',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], name='fk_user__coupon_coupon_id_coupon'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user__coupon_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'coupon_id', name='pk_user__coupon')
    )
    op.drop_table('user_coupon')
    # ### end Alembic commands ###
